-- 任务进度汇报表
CREATE TABLE IF NOT EXISTS task_progress_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    task_id BIGINT COMMENT '任务ID',
    task_name VARCHAR(200) COMMENT '任务名称',
    employee_id BIGINT COMMENT '员工ID',
    employee_name VARCHAR(100) COMMENT '员工姓名',
    report_type TINYINT COMMENT '汇报类型(1:日报, 2:周报, 3:月报, 4:项目汇报, 5:紧急汇报)',
    report_title VARCHAR(200) COMMENT '汇报标题',
    report_content TEXT COMMENT '汇报内容',
    progress INT DEFAULT 0 COMMENT '完成进度(0-100%)',
    work_duration INT COMMENT '工作时长(分钟)',
    work_results TEXT COMMENT '工作成果',
    problems TEXT COMMENT '遇到的问题',
    solutions TEXT COMMENT '解决方案',
    next_plan TEXT COMMENT '下一步计划',
    support_needed TEXT COMMENT '需要支持',
    work_location VARCHAR(200) COMMENT '工作地点',
    work_mode TINYINT COMMENT '工作模式(1:办公室, 2:远程, 3:混合)',
    attachments VARCHAR(500) COMMENT '附件文件',
    report_status TINYINT DEFAULT 1 COMMENT '汇报状态(1:待审核, 2:已通过, 3:需修改, 4:已驳回)',
    reviewer_id BIGINT COMMENT '审核人ID',
    reviewer_name VARCHAR(100) COMMENT '审核人姓名',
    review_time DATETIME COMMENT '审核时间',
    review_comment TEXT COMMENT '审核意见',
    quality_score TINYINT COMMENT '质量评分(1-5分)',
    efficiency_score TINYINT COMMENT '效率评分(1-5分)',
    attitude_score TINYINT COMMENT '态度评分(1-5分)',
    overall_score DECIMAL(3,1) COMMENT '综合评分',
    is_abnormal TINYINT DEFAULT 0 COMMENT '是否异常(0:否, 1:是)',
    abnormal_reason TEXT COMMENT '异常原因',
    supervision_note TEXT COMMENT '监督备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by VARCHAR(50) COMMENT '创建人',
    update_by VARCHAR(50) COMMENT '更新人',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志(0:未删除,1:已删除)',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    INDEX idx_task_id (task_id),
    INDEX idx_employee_id (employee_id),
    INDEX idx_report_type (report_type),
    INDEX idx_report_status (report_status),
    INDEX idx_create_time (create_time),
    INDEX idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务进度汇报表';

