package com.aicustomer.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 * 任务提醒实体类
 * 
 * @author AI Customer Management System
 * @version 1.0.0
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class TaskReminder extends BaseEntity {
    
    /**
     * 提醒标题
     */
    private String title;
    
    /**
     * 提醒内容
     */
    private String content;
    
    /**
     * 提醒类型 (1:关键日期, 2:跟进提醒, 3:机会提醒, 4:风险预警)
     */
    private Integer reminderType;
    
    /**
     * 关联客户ID
     */
    private Long customerId;
    
    /**
     * 关联客户姓名
     */
    private String customerName;
    
    /**
     * 提醒时间
     */
    private LocalDateTime reminderTime;
    
    /**
     * 截止时间
     */
    private LocalDateTime deadline;
    
    /**
     * 优先级 (1:低, 2:中, 3:高, 4:紧急)
     */
    private Integer priority;
    
    /**
     * 提醒状态 (1:待提醒, 2:已提醒, 3:已完成, 4:已取消, 5:已过期)
     */
    private Integer status;
    
    /**
     * 负责人员ID
     */
    private Long assignedUserId;
    
    /**
     * 负责人员姓名
     */
    private String assignedUserName;
    
    /**
     * 提醒方式 (1:系统内, 2:邮件, 3:短信, 4:微信, 5:全部)
     */
    private Integer reminderMethod;
    
    /**
     * 提醒频率 (1:一次性, 2:每日, 3:每周, 4:每月)
     */
    private Integer frequency;
    
    /**
     * 重复次数
     */
    private Integer repeatCount;
    
    /**
     * 已重复次数
     */
    private Integer repeatedCount;
    
    /**
     * 下次提醒时间
     */
    private LocalDateTime nextReminderTime;
    
    /**
     * 完成时间
     */
    private LocalDateTime completedTime;
    
    /**
     * 完成结果
     */
    private String completionResult;
    
    /**
     * 客户响应时间
     */
    private LocalDateTime customerResponseTime;
    
    /**
     * 客户响应内容
     */
    private String customerResponse;
    
    /**
     * 提醒效果评分 (1-5分)
     */
    private Integer effectivenessScore;
    
    /**
     * 关联业务ID
     */
    private Long businessId;
    
    /**
     * 关联业务类型
     */
    private String businessType;
    
    /**
     * 提醒规则ID
     */
    private Long ruleId;
    
    /**
     * 是否自动生成
     */
    private Boolean isAutoGenerated;
    
    /**
     * 生成来源
     */
    private String generatedFrom;
}

